### ISSUE TITLE
cannot open source file "bsp_api.h" (dependency of "Arduino.h")

### ISSUE THREAD

**Issue by LYB030** [maxgerhardt/platform-renesas#1]
build and upload works ,but vscode always show below error
<img width="1019" alt="image" src="https://github.com/maxgerhardt/platform-renesas/assets/42745293/8aa5a8e5-ee3d-41d2-997a-49b3bd285e81">

**Comment by maxgerhardt** [comment]
I can't reproduce this error.

![image](https://github.com/maxgerhardt/platform-renesas/assets/26485477/925955a6-3f02-44f6-8a8c-3e05b2160415)

Are you using the latest VSCode + C/C++ extension? 

Do you have conflicting extensions installed?

**Comment by maxgerhardt** [comment]
Specifically, `bsp_api.h` exists in 

![image](https://github.com/maxgerhardt/platform-renesas/assets/26485477/cf136526-7f12-407f-bcb5-2879433435a6)

This path is referenced in the `c_cpp_properties.json` in the compilerArg's `@` file
![image](https://github.com/maxgerhardt/platform-renesas/assets/26485477/b68c2304-88f4-481f-8928-05cc9f54447b)
![image](https://github.com/maxgerhardt/platform-renesas/assets/26485477/583e1d9e-47da-46c0-bee1-37bbe59ef5e9)

**Comment by LYB030** [comment]
i try to reinstall everything, i still got this error below is c_cpp.json
//
// !!! WARNING !!! AUTO-GENERATED FILE!
// PLEASE DO NOT MODIFY IT AND USE "platformio.ini":
// https://docs.platformio.org/page/projectconf/section_env_build.html#build-flags
//
{
    "configurations": [
        {
            "name": "PlatformIO",
            "includePath": [
                "D:/plotformio/test/include",
                "D:/plotformio/test/src",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/cores/arduino",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/cores/arduino/api/deprecated",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/cores/arduino/api/deprecated-avr-comp",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/cores/arduino/tinyusb",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/variants/UNOWIFIR4",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/AnalogWave",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/Arduino_CAN/src",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/Arduino_FreeRTOS/src",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/Arduino_LED_Matrix/src",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/BlockDevices",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/EEPROM/src",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/ESPhost/src",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/Ethernet/src",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/FATFilesystem",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/HID",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/LittleFilesystem",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/RTC/src",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/SE05X/src",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/SPI",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/SSLClient/src",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/SoftwareSerial/src",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/Storage",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/UsbHostMsd",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/UsbMsd",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/WiFi/src",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/WiFiS3/src",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/Wire",
                "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/lwIpWrapper/src",
                ""
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": true,
                "path": [
                    "D:/plotformio/test/include",
                    "D:/plotformio/test/src",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/cores/arduino",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/cores/arduino/api/deprecated",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/cores/arduino/api/deprecated-avr-comp",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/cores/arduino/tinyusb",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/variants/UNOWIFIR4",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/AnalogWave",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/Arduino_CAN/src",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/Arduino_FreeRTOS/src",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/Arduino_LED_Matrix/src",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/BlockDevices",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/EEPROM/src",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/ESPhost/src",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/Ethernet/src",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/FATFilesystem",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/HID",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/LittleFilesystem",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/RTC/src",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/SE05X/src",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/SPI",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/SSLClient/src",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/SoftwareSerial/src",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/Storage",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/UsbHostMsd",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/UsbMsd",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/WiFi/src",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/WiFiS3/src",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/Wire",
                    "C:/Users/94837/.platformio/packages/framework-arduinorenesas/libraries/lwIpWrapper/src",
                    ""
                ]
            },
            "defines": [
                "PLATFORMIO=60108",
                "NO_USB",
                "BACKTRACE_SUPPORT",
                "ARDUINO_UNOWIFIR4",
                "ARDUINO_UNOR4_WIFI",
                "ARDUINO_FSP",
                "CFG_TUSB_MCU=OPT_MCU_RAXXX",
                "_RA_CORE=CM4",
                "_RENESAS_RA_",
                "ARDUINO=10819",
                "ARDUINO_ARCH_RENESAS",
                "F_CPU=48000000L",
                "_XOPEN_SOURCE",
                ""
            ],
            "cStandard": "gnu11",
            "cppStandard": "gnu++17",
            "compilerPath": "C:/Users/94837/.platformio/packages/toolchain-gccarmnoneeabi/bin/arm-none-eabi-gcc.exe",
            "compilerArgs": [
                "-mcpu=cortex-m4",
                "-mfloat-abi=hard",
                "-mfpu=fpv4-sp-d16",
                "-mthumb",
                "-iprefixC:Users94837.platformiopackagesframework-arduinorenesas",
                "@C:Users94837.platformiopackagesframework-arduinorenesasvariantsUNOWIFIR4includes.txt",
                ""
            ]
        }
    ],
    "version": 4
}
<img width="904" alt="image" src="https://github.com/maxgerhardt/platform-renesas/assets/42745293/fb6778f4-4c71-4855-9810-1b5b7e8cfccc">

**Comment by maxgerhardt** [comment]
```
"-iprefixC:Users94837.platformiopackagesframework-arduinorenesas",
"@C:Users94837.platformiopackagesframework-arduinorenesasvariantsUNOWIFIR4includes.txt",
""
```
Does it really appear like that without any `/`? 

Please use code blocks (tripple backtrick at start and end) to ensure I see the proper file content and not some Markdown interpreted version.

**Comment by LYB030** [comment]
![image](https://github.com/maxgerhardt/platform-renesas/assets/42745293/f51c7333-7ad3-4062-81d6-d25cc91f0118)
Here is the full code

**Comment by maxgerhardt** [comment]
Okay so really all the path seperating `/` are just **gone**. That's not good at all. Are you running with the latest PlatformIO core? [CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) -> `pio upgrade --dev` --> Ctrl + Shift + P -> Reload Window, to update.

Is your VSCode connceted to some Windows-Subsystem-for-Linux (WSL) instance or a docker container? (lower left conenct icon in VSCode)

What's the exact VSCode version?

What's the version of the Microsoft C/C++ extension in VSCode?

![image](https://github.com/maxgerhardt/platform-renesas/assets/26485477/0a889927-4e7e-4076-926b-4de862482312)

**Comment by LYB030** [comment]
the vocode version is 
Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Date: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

and the c/c++ extension is v1.16.3
i upgrade the CLI to dev, but the problem is still exist.i am not in any wsl connect or docker container

**Comment by LYB030** [comment]
i try to install it on other Windows computer got same problem

**Comment by maxgerhardt** [comment]
Okay I have the same VSCode version and same C/C++ extension version and also the latest core dev version but the problem won't appear to me on Linux at least. Can't test on Windows right now.

We did have a similiar problem in that with https://github.com/platformio/builder-framework-arduino-core-mbed/issues/4 but that was a VSCode issue. Here it seems PlatformIO is not outputting the correct `c_cpp_properties.json` because it's missing all the path seperators for the `-iprefix` and `@<file>` arguments.

In any case, I just pushed a workaround against this: https://github.com/maxgerhardt/platform-renesas/commit/0b24d0c8966d492de36c9d5dc0e2e7968a682328

Please [open a PlatformIO core CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) and update using
```
pio pkg update -g -p renesas
```
Then in the project, Ctrl+Shift+P -> Rebuild Intellisense. That should regenerate `.vscode/c_cpp_properties.json` with a list of expanded includes instead of `-iprefix @<file>`.

**Comment by LYB030** [comment]
Great, problem solved! vscode doesn't report any errors about includepath anymore.thanks!

**Comment by lmolter54** [comment]
I did everything mentioned in the thread of responses. Still get arm-none-eabi-g++: error: 4: No such file or directory

**Comment by maxgerhardt** [comment]
The compiler not being found is a different error. Can you open a new issue with the output of [CLI](https://github.com/Community-PIO-CH32V/ch32-pio-projects#update-via-platformio-core-cli) -> `pio run -v -j1`?

**Comment by maxgerhardt** [comment]
@LYB030 can I ask you to recheck if you have the same intellisense with the official PlatofrmIO platform now? Just go into your `platformio.ini` and use
```ini
platform = https://github.com/platformio/platform-renesas-ra.git
```
instead of the previous  value.

**Comment by LYB030** [comment]
> 

Unfortunately, the error of intellisense is back after change platform = https://github.com/platformio/platform-renesas-ra.git

` "compilerArgs": [
                "-mcpu=cortex-m4",
                "-mfloat-abi=hard",
                "-mfpu=fpv4-sp-d16",
                "-mthumb",
                "-iprefixC:Users94837.platformiopackagesframework-arduinorenesas-uno",
                "@C:Users94837.platformiopackagesframework-arduinorenesas-unovariantsUNOWIFIR4includes.txt",
                ""
            ]`

**Comment by maxgerhardt** [comment]
Thanks for the back report, I've raised an issue for this per link above. Please watch for any changes there.
