### ISSUE TITLE
Flashing using `dfu-util` reports invalid status

### ISSUE THREAD

**Issue by vshymanskyy** [maxgerhardt/platform-renesas#2]
```
Download        [====================     ]  80%        40320 bytes
Download        [=====================    ]  84%        42368 bytes
Download        [======================   ]  88%        44352 bytes
Download        [=======================  ]  92%        46400 bytes
Download        [======================== ]  96%        48384 bytes
Download        [=========================] 100%        50316 bytes
Download done.
DFU state(7) = dfuMANIFEST, status(0) = No error condition is present
DFU state(2) = dfuIDLE, status(0) = No error condition is present
Done!
Resetting USB to switch back to Run-Time mode
*** [upload] Error 251
========================== [FAILED] Took 12.62 seconds ==========================

Environment    Status    Duration
-------------  --------  ------------
portentaC33    FAILED    00:00:12.620

```

Clearly, the device was flashed correctly.
@maxgerhardt  The reason for this is the `dfu-util -R` flag, which for some reason exits with code 251.

**Comment by maxgerhardt** [comment]
I thought I could get away with PlatformIO's built-in `dfu-util` version and `-R` instead of the original Arduino IDE one with `-Q`, but apparently this doesn't work on all systems or with the Portenta C33. Magically it works fine on my Windows 10+ Uno R4 Minima board.

```
Download        [======================   ]  90%        30528 bytes
Download        [=======================  ]  92%        31040 bytes
Download        [======================== ]  96%        32384 bytes
Download        [=========================] 100%        33640 bytes
Download done.
DFU state(7) = dfuMANIFEST, status(0) = No error condition is present
DFU state(2) = dfuIDLE, status(0) = No error condition is present
Done!
Resetting USB to switch back to Run-Time mode
Delaying 2s for USB serial enumeration...
======= [SUCCESS] Took 17.28 seconds =======
```
I'll switch the platform to use the same dfu-util version and use `-Q` shortly.

**Comment by maxgerhardt** [comment]
I've pushed https://github.com/maxgerhardt/platform-renesas/commit/d4bd5d22bcc17d2d1e91f6942f280fc3a2c308cc (and https://github.com/maxgerhardt/platform-renesas/commit/8c4f72fe6dca4abb6370985312a693a71ccf9574, woops) to fix this. It behaves the same still on Windows for me.

Can you open a [PlatformIO core CLI](https://github.com/Community-PIO-CH32V/ch32-pio-projects#update-via-platformio-core-cli) -> `pio pkg update -g -p renesas` and then try uploading to the Portenta C33 again? Does it work this time?

**Comment by vshymanskyy** [comment]
```
Environment    Status    Duration
-------------  --------  ------------
portentaC33    SUCCESS   00:00:14.826
```
