### ISSUE TITLE
Uploading problems Manjaro

### ISSUE THREAD

**Issue by stan754** [maxgerhardt/platform-renesas#4]
Hey I tried to upload a small test program to see if it works but I can't get the upload to work.
Everything else works I can also use platformio for other boards just not this one.
This is the error I get:
![image](https://github.com/maxgerhardt/platform-renesas/assets/25099010/8fbb4b9d-1f89-460f-9c9b-48f10764e823)

edit: I tried both the stable and development versions like in the readme

**Comment by maxgerhardt** [comment]
My bad, I uploaded the wrong bossac binary for Linux + Mac (`bossac-1.9.1-arduino1` instead of `bossac-1.9.1-arduino5`). I just confirmed it does work when I manually updated the binary.

Will be updated shortly.

**Comment by maxgerhardt** [comment]
https://github.com/maxgerhardt/tool-bossac-1.9.1/commit/41214fd85ff0a295eb4bebc6118f61c33a7fdfdb was pushed. Can you please

```
rm -rf ~/.platformio/packages/tool-bossac*
```
and try and reupload? You may need to unplug + replug your board.

*Edit: Path fixed.*

**Comment by stan754** [comment]
Thanks this fixed it, it even uploads faster (and every time instead of only sometimes like arduino ide 2.0)

For other people who have the same problem for me the path was:
`rm -rf ~/.platformio/packages/tool-bossac* `
